server:
  port: 8888
spring:
  application:
    name: wowcare-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/preshitakoli-atoconn/wowcare-config-server.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka